Request for code review
eapenzacharias/enumerable pull request #1
Opened 2019-07-05 23:14 UTC by eapenzacharias

2019-07-06 03:06 UTC, mcrd25 reviewed
# Wow great attempt! A couple of changes till 🚀 
Hi Eapen 👋,

## Concerning project specifications
**This is where you stand:**
- [x] should have working my_each 
- [x] should have working my_each_with_index
- [x] should have working my_select 
- [x] should have working my_all? 
- [x] should have working my_none? 
- [x] should have working my_count 
- [x] should have working my_map
- [x] should have working my_inject 

## Concerning crucial requirements that make project work

**This is where you stand**
- [x] Verify if the project should be done solo or collaboratively and that the commit history reflects that
- [x] The project has a descriptive README.md

## Review Comments

Check out my review comments, please address them to make your project work! Also, please recognize that all comments are to be addressed except for those that are listed as suggested.

**Really great project so far!** 😄 

## Additional Suggestions
- I noticed your indentation is pretty wide, maybe try to stick with 2 spaces 😅 

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +    def my_count
Your `my_count` method should also consider when block not given
It should also consider when arg is passed. i.e count would only count if array item == arg
so the method could be like
```ruby
def my_count(arg=nil)
  counter = 0
  if block_given?
    self.my_each do |value|
           if yield(value)
               count+=1
           end
     end
  else
   # do stuff if arg passed
  end
  count
end
```

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +    def my_count
also if neither arg  or block given it should return the length of array etc.

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +    def my_count
Please address these comments!

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +    def my_all?
Hey, this is a great attempt, but it gives the wrong result in code review tests.
Here's why:
it only returns false but never has an occurrence for returning true.

You can do this by simply adding `true` before the method or adding `return true`

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +                 return true
Similar issue as with `my_all` only ever returns true. What about false? This causes the method to fail tests

2019-07-06 03:06 UTC, mcrd25 commented on blocks.rb
> +    def my_none?
SAme as with `my_all?`

2019-07-06 03:07 UTC, mcrd25 requested changes
# Wow great attempt! A couple of changes till 🚀 
Hi Eapen 👋,

## Concerning project specifications
**This is where you stand:**
- [x] should have working my_each 
- [x] should have working my_each_with_index
- [x] should have working my_select 
- [x] should have working my_all? 
- [x] should have working my_none? 
- [x] should have working my_count 
- [x] should have working my_map
- [x] should have working my_inject 

## Concerning crucial requirements that make project work

**This is where you stand**
- [x] Verify if the project should be done solo or collaboratively and that the commit history reflects that
- [x] The project has a descriptive README.md

## Review Comments

Check out my review comments, please address them to make your project work! Also, please recognize that all comments are to be addressed except for those that are listed as suggested.

**Really great project so far!** 😄 

## Additional Suggestions
- I noticed your indentation is pretty wide, maybe try to stick with 2 spaces 😅 

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-07-08 17:05 UTC, eapenzacharias commented on blocks.rb
> +    def my_all?
Pure carelessness. Sorry for that

2019-07-08 18:43 UTC, AdnanAfsari approved these changes
Hello @eapenzacharias @mcrd25 Congratulations 👍 

Nice work , looks good, You can merge the branch now.

Happy Coding :)

2019-07-08 18:44 UTC, merged